"""empty message

Revision ID: 55eaed677991
Revises: 
Create Date: 2020-06-04 16:25:58.548987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55eaed677991'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=80), nullable=False),
    sa.Column('longitude', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude'),
    sa.UniqueConstraint('message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    # ### end Alembic commands ###
